version: '3.3'
services:
### MySQL Container
  mysql:
    image: mysql:8
    container_name: mysql-playground
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d